version: '3.8'

services:
  cobaltia-bot:
    build: ./
    container_name: cobaltia-bot
    depends_on:
      - cobaltia-redis
    restart: unless-stopped

  cobaltia-redis:
    image: 'redis:alpine'
    container_name: cobaltia-redis
    restart: unless-stopped
