version: '3.8'

services:
  cobaltia-bot:
    build: ./
    container_name: cobaltia-bot
    depends_on:
      - cobaltia-redis
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

  cobaltia-redis:
    image: 'redis:alpine'
    container_name: cobaltia-redis
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
