name: Database Migration
on:
  push:
    paths:
      - prisma/migrations/**
    branches:
      - main

jobs:
  deploy:
    runs-on: blacksmith-4vcpu-ubuntu-2404
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 9
      - name: Install Node v20
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Apply Pending Migrations
        run: pnpm npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.COBALTIA_DATABASE_URL }}
